services:
  db:
    container_name: postgres-precificacao
    image: postgres:17.4-alpine3.21
    env_file:
      - ../../../../.env.development
    ports:
      - 6543:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
