import ActiveLink from '@ui/active-link';
import { Toaster } from '@ui/shadcn/sonner';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className='border-b'>
          <div className='text-2xl p-8 text-center border-b uppercase'>
            Precificação de Bolsas
          </div>
          <nav className='flex justify-center gap-2.5 my-1'>
            <ActiveLink
              href='/'
              className='px-5 py-1.5 hover:bg-black hover:text-white'
            >
              Início
            </ActiveLink>
            <ActiveLink
              href='/materials'
              className='px-5 py-1.5 hover:bg-black hover:text-white'
            >
              Materiais
            </ActiveLink>
            <ActiveLink
              href='/bags'
              className='px-5 py-1.5 hover:bg-black hover:text-white'
            >
              Bolsas
            </ActiveLink>
          </nav>
        </header>
        <div className='max-w-5xl mx-auto mt-10'>{children}</div>
        <Toaster />
      </body>
    </html>
  );
}
