import { Button } from '@ui/shadcn/button';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased justify-center p-5`}
      >
        <header>
          <menu className='pb-5 space-x-2.5'>
            <Link href='/'>
              <Button variant={'outline'}>Início</Button>
            </Link>
            <Link href='/materials'>
              <Button variant={'outline'}>Materiais</Button>
            </Link>
            <Link href='/bags'>
              <Button variant={'outline'}>Bolsas</Button>
            </Link>
          </menu>
        </header>
        {children}
      </body>
    </html>
  );
}
